language: python

virtualenv:
    system_site_packages: true

python:
    - "2.7"

before_install:
    - sudo apt-get update -qq -y
    - sudo pip install git+https://github.com/azvoleff/pyabm.git#egg=pyabm
    - sudo apt-get install -qq python-numpy python-matplotlib python-gdal gdal-bin python-tables python-numexpr

install:
    - pip install .

script: nosetests

notifications:
  email:
    on_success: change
    on_failure: change
