#!/usr/bin/env Rscript
###############################################################################
# Script used to generate a synthetic dataset of individuals, households, and 
# neighborhoods to be used in running the ChitwanABM. This allows both modeling 
# the full population (as the CVFS is only a partial sample), and also allows 
# redistributing the model with an unrestricted population dataset. The CVFS 
# data is restricted access to protect respondent confidentiality.
###############################################################################
#
# Copyright 2011 Alex Zvoleff
#
# This file is part of the ChitwanABM agent-based model.
#
# rcparams.default provides the default values that are used for the ChitwanABM 
# if no local ChitwanABMrc file is provided when the model is run, or that are 
# used if any parameters are missing from it.
# 
# Parameters are specifed in the following format:
#
# 	'parameter_name' : [default_value | validation_function] # Comment
#
# where 'parameter_name' is the name of the parameter, 'default_value' is the 
# default value, and validation_function one of the set of validation functions 
# listed in rcsetup.py. The validation function is used to ensure that only 
# valid values are provided to the model.
#
# Any comments or newline characters after the 'START OF RC DEFINITION' line 
# below will be included in any rc files built using the 'write_RC_file' 
# function  in rcsetup.py. The order in which the parameters  are specified in 
# this file will be retained when rc files are generated by the 'write_RC_file' 
# function.
#
# Contact Alex Zvoleff in the Department of Geography at San Diego State 
# University with any comments or questions. See the README.txt file for 
# contact information.

load("/media/Local_Secure/ChitwanABM_init/hhrel.Rdata")
load("/media/Local_Secure/ChitwanABM_init/hhag.Rdata")
load("/media/Local_Secure/ChitwanABM_init/neigh.Rdata")

# First convert the LULC data to get a total NBH area field, and then make all 
# the other fields percentages of this total.



###############################################################################
# Output data. Synthetic data is NOT restricted so it can be distributed 
# freely.
save(hhrel.syn, file="/media/Local_Secure/ChitwanABM_init/hhrel.Rdata")
save(hhag.syn, file="/media/Local_Secure/ChitwanABM_init/hhag.Rdata")
save(neigh.syn, file="/media/Local_Secure/ChitwanABM_init/neigh.Rdata")
