#!/usr/bin/env Rscript
###############################################################################
# Plots the pop data from a model run.
###############################################################################
#
# Copyright 2011 Alex Zvoleff
#
# This file is part of the ChitwanABM agent-based model.
#
# rcparams.default provides the default values that are used for the ChitwanABM 
# if no local ChitwanABMrc file is provided when the model is run, or that are 
# used if any parameters are missing from it.
# 
# Parameters are specifed in the following format:
#
# 	'parameter_name' : [default_value | validation_function] # Comment
#
# where 'parameter_name' is the name of the parameter, 'default_value' is the 
# default value, and validation_function one of the set of validation functions 
# listed in rcsetup.py. The validation function is used to ensure that only 
# valid values are provided to the model.
#
# Any comments or newline characters after the 'START OF RC DEFINITION' line 
# below will be included in any rc files built using the 'write_RC_file' 
# function  in rcsetup.py. The order in which the parameters  are specified in 
# this file will be retained when rc files are generated by the 'write_RC_file' 
# function.
#
# Contact Alex Zvoleff in the Department of Geography at San Diego State 
# University with any comments or questions. See the README.txt file for 
# contact information.

require(ggplot2, quietly=TRUE)

PLOT_WIDTH = 8.33
PLOT_HEIGHT = 5.53

source("calc_NBH_stats.R")

DATA_PATH <- commandArgs(trailingOnly=TRUE)[1]

pop.results <- calc_NBH_pop(DATA_PATH)

# Make two separate stacks - one of monthly event data and one of total hs and 
# total marriages. Stack them so they can easily be color-coded with ggplot2.
events <- with(pop.results, data.frame(time.Robj=time.Robj, marr, births, deaths))
events <- stack(events)
events <- cbind(time.Robj=rep(pop.results$time.Robj, 3), events)
names(events)[2:3] <- c("events", "Event_type")

num.hs.marr <- with(pop.results, data.frame(time.Robj=time.Robj, num_hs, num_marr))
num.hs.marr <- stack(num.hs.marr)
num.hs.marr <- cbind(time.Robj=rep(pop.results$time.Robj,2), num.hs.marr)
names(num.hs.marr)[2:3] <- c("num", "Pop_type")

# First plot monthly event data
theme_update(theme_grey(base_size=18))
# Plot thinner lines so this busy plot is easier to read.
update_geom_defaults("line", aes(size=.5))
qplot(pop.results$time.Robj, events, geom="line", colour=Event_type, xlab="Year",
        ylab="Number of Events", data=events)
ggsave(paste(DATA_PATH, "pop_events.png", sep="/"), width=PLOT_WIDTH, height=PLOT_HEIGHT,
        dpi=300)

# Now plot total households and total marriages
qplot(time.Robj, num, geom="line", colour=Pop_type, xlab="Year",
        ylab="Population", data=num.hs.marr)
ggsave(paste(DATA_PATH, "pop_num_hs_marr.png", sep="/"), width=PLOT_WIDTH,
        height=PLOT_HEIGHT, dpi=300)

# Plot total population
update_geom_defaults("line", aes(size=1))
qplot(time.Robj, num_psn, geom="line", xlab="Year",
        ylab="Population", data=pop.results)
ggsave(paste(DATA_PATH, "pop_num_psn.png", sep="/"), width=PLOT_WIDTH,
        height=PLOT_HEIGHT, dpi=300)

# Plot fw consumption in metric tons
qplot(time.Robj, fw_usage_kg/1000, geom="line", xlab="Year",
        ylab="Metric Tons of Fuelwood", data=pop.results)
ggsave(paste(DATA_PATH, "fw_usage.png", sep="/"), width=PLOT_WIDTH,
        height=PLOT_HEIGHT, dpi=300)
