#!/usr/bin/env Rscript
###############################################################################
# Plots the individual person data from a model run.
###############################################################################
#
# Copyright 2011 Alex Zvoleff
#
# This file is part of the ChitwanABM agent-based model.
#
# rcparams.default provides the default values that are used for the ChitwanABM 
# if no local ChitwanABMrc file is provided when the model is run, or that are 
# used if any parameters are missing from it.
# 
# Parameters are specifed in the following format:
#
# 	'parameter_name' : [default_value | validation_function] # Comment
#
# where 'parameter_name' is the name of the parameter, 'default_value' is the 
# default value, and validation_function one of the set of validation functions 
# listed in rcsetup.py. The validation function is used to ensure that only 
# valid values are provided to the model.
#
# Any comments or newline characters after the 'START OF RC DEFINITION' line 
# below will be included in any rc files built using the 'write_RC_file' 
# function  in rcsetup.py. The order in which the parameters  are specified in 
# this file will be retained when rc files are generated by the 'write_RC_file' 
# function.
#
# Contact Alex Zvoleff in the Department of Geography at San Diego State 
# University with any comments or questions. See the README.txt file for 
# contact information.

require(epicalc)
require(ggplot2, quietly=TRUE)

PLOT_WIDTH = 8.33
PLOT_HEIGHT = 5.53
# Customize the ggplot2 theme
theme_update(theme_grey(base_size=18))
update_geom_defaults("line", aes(size=1))

DATA_PATH <- commandArgs(trailingOnly=TRUE)[1]

files <- list.files(DATA_PATH)
# Only match the model results folders - don't match any other folders or files 
# in the directory, as trying to read results from these other files/folders 
# would lead to an error.
files <- files[grep("^psns_time_[0-9]*.csv$", files)]
# Sort the files by timestep
files <- files[order(as.numeric(gsub("(^psns_time_)|(.csv$)", "", files)))]
pdf_file_path <- paste(DATA_PATH, "/psns_pop_pyramid.pdf", sep="") 
pdf(file=pdf_file_path)
hhsize <- c()
timesteps <-c()
for (psns_file in files) {
    timestep <- gsub("(^psns_time_)|(.csv$)", "",  psns_file)
    timesteps <- c(timesteps, timestep)
    full_file_path <- paste(DATA_PATH, "/", psns_file, sep="") 
    psns_data <- read.csv(full_file_path)
    # Cover ages from months to years
    psns_data$age <- psns_data$age/12
    pyramid(psns_data$age, psns_data$gender, main=paste("Timestep", timestep, sep=" "))
    hhsize <- c(hhsize, mean(table(psns_data$hid)))
}
dev.off()

time.values <- read.csv(paste(DATA_PATH, "time.csv", sep="/"))
time.Robj <- as.Date(paste(time.values$time_date, "15", sep=","),
        format="%m/%Y,%d")
time.values <- cbind(time.values, time.Robj=time.Robj)
time.Robj <- time.values$time.Robj[time.values$timestep %in% timesteps]

qplot(time.Robj, hhsize, geom="line", xlab="Year",
        ylab="Mean Household Size (number of persons)")
ggsave(paste(DATA_PATH, "hhsize.png", sep="/"), width=PLOT_WIDTH,
        height=PLOT_HEIGHT, dpi=300)
