###############################################################################
# Loads the CVFS data and prints summary info about several people, households, 
# and neighborhoods that is used by the test.py script to verify the operation 
# of the ChitwanABM model.
###############################################################################
#
# Copyright 2011 Alex Zvoleff
#
# This file is part of the ChitwanABM agent-based model.
#
# rcparams.default provides the default values that are used for the ChitwanABM 
# if no local ChitwanABMrc file is provided when the model is run, or that are 
# used if any parameters are missing from it.
# 
# Parameters are specifed in the following format:
#
# 	'parameter_name' : [default_value | validation_function] # Comment
#
# where 'parameter_name' is the name of the parameter, 'default_value' is the 
# default value, and validation_function one of the set of validation functions 
# listed in rcsetup.py. The validation function is used to ensure that only 
# valid values are provided to the model.
#
# Any comments or newline characters after the 'START OF RC DEFINITION' line 
# below will be included in any rc files built using the 'write_RC_file' 
# function  in rcsetup.py. The order in which the parameters  are specified in 
# this file will be retained when rc files are generated by the 'write_RC_file' 
# function.
#
# Contact Alex Zvoleff in the Department of Geography at San Diego State 
# University with any comments or questions. See the README.txt file for 
# contact information.

library("foreign")
census <- read.xport("/media/Restricted/Data/ICPSR_0538_Restricted/da04538-0004_REST.xpt")
hhrel <- read.xport("/media/Restricted/Data/ICPSR_0538_Restricted/da04538-0016_REST.xpt")
hhag <- read.xport("/media/Restricted/Data/ICPSR_0538_Restricted/da04538-0002_REST.xpt")
neigh <- read.xport("/media/Restricted/Data/ICPSR_0538_Restricted/da04538-0014_REST.xpt")

# Pull out an entire household to test how the agents are read in to the model
# Use HHID=905 (a random household)
census$CENGENDR[census$CENGENDR==1] <- "male"
census$CENGENDR[census$CENGENDR==2] <- "female"
census.hh <- census[which(census$HHID=="905"),]
# Convert ages expressed in years to ages in months, as used in the model
AGEMNTHS <- census.hh$CENAGE*12
census.hh <- with(census.hh, data.frame(RESPID, CENAGE, AGEMNTHS, CENGENDR))

hhrel.hh <- hhrel[which(hhrel$HHID=="905"),]
hhrel.hh <- with(hhrel.hh, data.frame(RESPID, SUBJECT, PARENT1, PARENT2, SPOUSE1, SPOUSE2, SPOUSE3))

hh <- merge(hhrel.hh, census.hh, by="RESPID")
